import 'dart:convert';
import 'dart:io';

void main() {
  final l10nDir = Directory('lib/l10n');
  final files = l10nDir.listSync().whereType<File>().where((f) => f.path.endsWith('.arb'));

  final additions = {
    'en': {
      "pdfTitle": "Ovya — PCOS Health Report",
      "pdfDateGenerated": "Date Generated: {date}",
      "@pdfDateGenerated": { "placeholders": { "date": { "type": "String" } } },
      "pdfDisclaimer": "This report is for informational purposes only. Please consult a qualified healthcare provider.",
      "pdfGeneratedBy": "Generated by Ovya — Women's Health Companion",
      "patientDetails": "Patient Details",
      "patientNameLabel": "Name: {name}",
      "@patientNameLabel": { "placeholders": { "name": { "type": "String" } } },
      "reportDateLabel": "Report Date: {date}",
      "@reportDateLabel": { "placeholders": { "date": { "type": "String" } } },
      "riskAssessment": "Risk Assessment",
      "riskLevelLabel": "Risk Level:",
      "scoreLabel": "Score:",
      "pcosTypeHintLabel": "PCOS Type Hint:",
      "explanationLabel": "Explanation:",
      "symptomsLast30Days": "Symptoms Reported (Last 30 Days)",
      "noSymptoms30Days": "No symptoms logged in the last 30 days.",
      "tableHeaderDate": "Date",
      "tableHeaderSymptoms": "Symptoms",
      "tableHeaderMood": "Mood/Notes",
      "tableNone": "None",
      "low": "Low",
      "medium": "Medium",
      "high": "High"
    },
    'hi': {
      "pdfTitle": "ओव्या — पीसीओएस स्वास्थ्य रिपोर्ट (PCOS Health Report)",
      "pdfDateGenerated": "उत्पन्न तिथि: {date}",
      "@pdfDateGenerated": { "placeholders": { "date": { "type": "String" } } },
      "pdfDisclaimer": "यह रिपोर्ट केवल सूचनात्मक उद्देश्यों के लिए है। कृपया एक योग्य डॉक्टर से परामर्श लें।",
      "pdfGeneratedBy": "ओव्या द्वारा उत्पन्न — महिला स्वास्थ्य साथी",
      "patientDetails": "रोगी विवरण",
      "patientNameLabel": "नाम: {name}",
      "@patientNameLabel": { "placeholders": { "name": { "type": "String" } } },
      "reportDateLabel": "रिपोर्ट तिथि: {date}",
      "@reportDateLabel": { "placeholders": { "date": { "type": "String" } } },
      "riskAssessment": "जोखिम मूल्यांकन",
      "riskLevelLabel": "जोखिम स्तर:",
      "scoreLabel": "स्कोर:",
      "pcosTypeHintLabel": "पीसीओएस (PCOS) प्रकार संकेत:",
      "explanationLabel": "व्याख्या:",
      "symptomsLast30Days": "पिछले 30 दिनों के लक्षण",
      "noSymptoms30Days": "पिछले 30 दिनों में कोई लक्षण दर्ज नहीं किया गया।",
      "tableHeaderDate": "तारीख़",
      "tableHeaderSymptoms": "लक्षण",
      "tableHeaderMood": "मूड/नोट्स",
      "tableNone": "कोई नहीं",
      "low": "कम",
      "medium": "मध्यम",
      "high": "उच्च"
    },
    'mr': {
      "pdfTitle": "ओव्या — पीसीओएस आरोग्य अहवाल",
      "pdfDateGenerated": "तयार केलेली तारीख: {date}",
      "@pdfDateGenerated": { "placeholders": { "date": { "type": "String" } } },
      "pdfDisclaimer": "हा अहवाल केवळ माहितीसाठी आहे. कृपया योग्य डॉक्टरांचा सल्ला घ्या.",
      "pdfGeneratedBy": "ओव्या द्वारे निर्मित — महिला आरोग्य साथी",
      "patientDetails": "रुग्णाचे तपशील",
      "patientNameLabel": "नाव: {name}",
      "@patientNameLabel": { "placeholders": { "name": { "type": "String" } } },
      "reportDateLabel": "अहवाल तारीख: {date}",
      "@reportDateLabel": { "placeholders": { "date": { "type": "String" } } },
      "riskAssessment": "धोका मूल्यांकन",
      "riskLevelLabel": "धोका पातळी:",
      "scoreLabel": "स्कोर:",
      "pcosTypeHintLabel": "पीसीओएस (PCOS) प्रकार संकेत:",
      "explanationLabel": "स्पष्टीकरण:",
      "symptomsLast30Days": "मागील ३० दिवसांतील लक्षणे",
      "noSymptoms30Days": "मागील ३० दिवसांत कोणतीही लक्षणे नोंदवली नाहीत.",
      "tableHeaderDate": "तारीख",
      "tableHeaderSymptoms": "लक्षणे",
      "tableHeaderMood": "मूड/नोट्स",
      "tableNone": "काहीही नाही",
      "low": "कमी",
      "medium": "मध्यम",
      "high": "जास्त"
    },
    'kn': {
      "pdfTitle": "ಓವ್ಯಾ — PCOS ಆರೋಗ್ಯ ವರದಿ",
      "pdfDateGenerated": "ರಚಿಸಿದ ದಿನಾಂಕ: {date}",
      "@pdfDateGenerated": { "placeholders": { "date": { "type": "String" } } },
      "pdfDisclaimer": "ಈ ವರದಿಯು ಕೇವಲ ಮಾಹಿತಿಗಾಗಿ. ದಯವಿಟ್ಟು ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ.",
      "pdfGeneratedBy": "ಓವ್ಯಾ ನಿಂದ ರಚಿಸಲಾಗಿದೆ — ಮಹಿಳಾ ಆರೋಗ್ಯ ಸಂಗಾತಿ",
      "patientDetails": "ರೋಗಿಯ ವಿವರಗಳು",
      "patientNameLabel": "ಹೆಸರು: {name}",
      "@patientNameLabel": { "placeholders": { "name": { "type": "String" } } },
      "reportDateLabel": "ವರದಿ ದಿನಾಂಕ: {date}",
      "@reportDateLabel": { "placeholders": { "date": { "type": "String" } } },
      "riskAssessment": "ಅಪಾಯದ ಮೌಲ್ಯಮಾಪನ",
      "riskLevelLabel": "ಅಪಾಯದ ಮಟ್ಟ:",
      "scoreLabel": "ಸ್ಕೋರ್:",
      "pcosTypeHintLabel": "PCOS ಪ್ರಕಾರದ ಸುಳಿವು:",
      "explanationLabel": "ವಿವರಣೆ:",
      "symptomsLast30Days": "ಕಳೆದ 30 ದಿನಗಳ ಲಕ್ಷಣಗಳು",
      "noSymptoms30Days": "ಕಳೆದ 30 ದಿನಗಳಲ್ಲಿ ಯಾವುದೇ ಲಕ್ಷಣಗಳನ್ನು ದಾಖಲಿಸಿಲ್ಲ.",
      "tableHeaderDate": "ದಿನಾಂಕ",
      "tableHeaderSymptoms": "ಲಕ್ಷಣಗಳು",
      "tableHeaderMood": "ಮೂಡ್/ಟಿಪ್ಪಣಿಗಳು",
      "tableNone": "ಯಾವುದೂ ಇಲ್ಲ",
      "low": "ಕಡಿಮೆ",
      "medium": "ಮಧ್ಯಮ",
      "high": "ಹೆಚ್ಚು"
    },
    'te': {
      "pdfTitle": "ఓవ్యా — PCOS ఆరోగ్య నివేదిక",
      "pdfDateGenerated": "సృష్టించబడిన తేదీ: {date}",
      "@pdfDateGenerated": { "placeholders": { "date": { "type": "String" } } },
      "pdfDisclaimer": "ఈ నివేదిక కేవలం సమాచారం కోసం మాత్రమే. దయచేసి అర్హత కలిగిన వైద్యుడిని సంప్రదించండి.",
      "pdfGeneratedBy": "ఓవ్యా ద్వారా రూపొందించబడింది — మహిళా ఆరోగ్య భాగస్వామి",
      "patientDetails": "రోగి వివరాలు",
      "patientNameLabel": "పేరు: {name}",
      "@patientNameLabel": { "placeholders": { "name": { "type": "String" } } },
      "reportDateLabel": "నివేదిక తేదీ: {date}",
      "@reportDateLabel": { "placeholders": { "date": { "type": "String" } } },
      "riskAssessment": "ప్రమాద అంచనా",
      "riskLevelLabel": "ప్రమాద స్థాయి:",
      "scoreLabel": "స్కోరు:",
      "pcosTypeHintLabel": "PCOS రకం సూచన:",
      "explanationLabel": "వివరణ:",
      "symptomsLast30Days": "గత 30 రోజుల లక్షణాలు",
      "noSymptoms30Days": "గత 30 రోజుల్లో ఎటువంటి లక్షణాలు నమోదు కాలేదు.",
      "tableHeaderDate": "తేదీ",
      "tableHeaderSymptoms": "లక్షణాలు",
      "tableHeaderMood": "మూడ్/గమనికలు",
      "tableNone": "ఏదీ లేదు",
      "low": "తక్కువ",
      "medium": "మధ్యస్థం",
      "high": "ఎక్కువ"
    }
  };

  for (var file in files) {
    var raw = file.readAsStringSync();
    var map = json.decode(raw) as Map<String, dynamic>;
    
    // detect locale
    String loc = map['@@locale'] as String;
    var addMap = additions[loc];
    if (addMap != null) {
      addMap.forEach((k, v) {
        if (!map.containsKey(k)) map[k] = v;
      });
      // pretty print
      final encoder = JsonEncoder.withIndent('  ');
      file.writeAsStringSync(encoder.convert(map));
      print('Updated \${file.path}');
    }
  }
}
