import 'dart:typed_data';
import 'package:flutter/material.dart' show Locale;
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:intl/intl.dart';
import 'package:ovya/l10n/gen/app_localizations.dart';

import '../../core/intelligence/detection_engine.dart';
import '../symptom_tracking/domain/symptom_entity.dart';

class ReportGenerator {
  Future<Uint8List> generateReport({
    required String patientName,
    required RiskResult riskResult,
    required List<SymptomEntity> recentLogs, // Mapped from SymphonyEntity logic
    required String language,
  }) async {
    final pdf = pw.Document();

    // Load localizer based on language directly
    final loc = lookupAppLocalizations(Locale(language));
    final nowStr = DateFormat.yMMMMd(language).format(DateTime.now());

    // Resolve recommendations keys to strings using our mapping helper
    final parsedRecs = riskResult.recommendations.map((key) => _getRecommendation(loc, key)).toList();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        header: (context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text('Ovya — PCOS Health Report', 
                style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.pink800)),
              pw.SizedBox(height: 6),
              pw.Text('Date Generated: $nowStr', style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey700)),
              pw.SizedBox(height: 12),
              pw.Divider(color: PdfColors.pink200, thickness: 2),
              pw.SizedBox(height: 20),
            ],
          );
        },
        footer: (context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.center,
            children: [
              pw.Divider(color: PdfColors.grey300),
              pw.SizedBox(height: 8),
              pw.Text(
                'This report is for informational purposes only. Please consult a qualified healthcare provider.', 
                style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600), 
                textAlign: pw.TextAlign.center
              ),
              pw.SizedBox(height: 4),
              pw.Text(
                'Generated by Ovya — Women\'s Health Companion', 
                style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600), 
                textAlign: pw.TextAlign.center
              ),
            ],
          );
        },
        build: (context) {
          return [
            // Patient Info
            pw.Text('Patient Details', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
            pw.SizedBox(height: 8),
            pw.Text('Name: $patientName', style: const pw.TextStyle(fontSize: 14)),
            pw.Text('Report Date: $nowStr', style: const pw.TextStyle(fontSize: 14)),
            pw.SizedBox(height: 24),

            // Risk Assessment Box
            pw.Container(
              padding: const pw.EdgeInsets.all(16),
              decoration: pw.BoxDecoration(
                border: pw.Border.all(color: PdfColors.pink300, width: 1.5),
                borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
                color: PdfColors.pink50,
              ),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text('Risk Assessment', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold, color: PdfColors.pink800)),
                  pw.Divider(color: PdfColors.pink200),
                  pw.SizedBox(height: 8),
                  
                  pw.Row(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Expanded(
                        child: pw.Column(
                          crossAxisAlignment: pw.CrossAxisAlignment.start,
                          children: [
                            pw.Text('Risk Level:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                            pw.Text(loc.riskLevel(riskResult.level), style: const pw.TextStyle(fontSize: 16, color: PdfColors.red800)),
                            pw.SizedBox(height: 8),
                            pw.Text('Score:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                            pw.Text('${riskResult.score} / 23', style: const pw.TextStyle(fontSize: 14)),
                          ],
                        ),
                      ),
                      pw.Expanded(
                        flex: 2,
                        child: pw.Column(
                          crossAxisAlignment: pw.CrossAxisAlignment.start,
                          children: [
                            if (riskResult.pcosTypeHint != null) ...[
                              pw.Text('PCOS Type Hint:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                              pw.Text('Your symptoms suggest ${_getPcosTypeName(loc, riskResult.pcosTypeHint!)} PCOS'),
                              pw.SizedBox(height: 8),
                            ],
                            pw.Text('Explanation:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                            pw.Text(riskResult.explanation),
                          ],
                        )
                      )
                    ]
                  ),
                ],
              ),
            ),
            pw.SizedBox(height: 24),

            // Recommendations
            pw.Text(loc.recommendations, style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
            pw.SizedBox(height: 8),
            ...parsedRecs.asMap().entries.map((entry) => pw.Padding(
              padding: const pw.EdgeInsets.only(bottom: 6),
              child: pw.Row(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text('${entry.key + 1}. ', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                  pw.Expanded(child: pw.Text(entry.value)),
                ],
              )
            )),
            pw.SizedBox(height: 24),

            // Logs Table
            pw.Text('Symptoms Reported (Last 30 Days)', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
            pw.SizedBox(height: 8),
            _buildLogsTable(recentLogs.take(10).toList(), language),
          ];
        },
      ),
    );

    return pdf.save();
  }

  pw.Widget _buildLogsTable(List<SymptomEntity> logs, String language) {
    if (logs.isEmpty) {
      return pw.Container(
        padding: const pw.EdgeInsets.all(12),
        decoration: pw.BoxDecoration(
          color: PdfColors.grey100,
          borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
        ),
        child: pw.Text('No symptoms logged in the last 30 days.', style: const pw.TextStyle(color: PdfColors.grey700)),
      );
    }

    final headers = ['Date', 'Symptoms', 'Mood/Notes'];
    
    final data = logs.map((log) {
      final dateStr = DateFormat.yMd(language).format(log.timestamp);
      
      final active = <String>[];
      if (log.irregularCycle) active.add('Irregular cycle');
      if (log.acne) active.add('Acne');
      if (log.weightGain) active.add('Weight gain');
      if (log.hairGrowth) active.add('Excess hair');
      if (log.moodIssues) active.add('Mood issues');
      if (log.hairThinning) active.add('Hair thinning');
      if (log.skinDarkening) active.add('Skin darkening');
      if (log.fatigue) active.add('Fatigue');
      if (log.sleepProblems) active.add('Sleep problems');
      if (log.bloating) active.add('Bloating');
      final sympStr = active.join(', ');
      
      final notes = log.notes ?? '-';

      return [dateStr, sympStr.isEmpty ? 'None' : sympStr, notes];
    }).toList();

    return pw.TableHelper.fromTextArray(
      headers: headers,
      data: data,
      headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white),
      headerDecoration: const pw.BoxDecoration(color: PdfColors.pink400),
      rowDecoration: const pw.BoxDecoration(border: pw.Border(bottom: pw.BorderSide(color: PdfColors.grey200, width: 0.5))),
      cellHeight: 30,
      cellPadding: const pw.EdgeInsets.all(6),
      cellAlignments: {
        0: pw.Alignment.topLeft,
        1: pw.Alignment.topLeft,
        2: pw.Alignment.topLeft,
      },
    );
  }

  String _getRecommendation(AppLocalizations loc, String key) {
    switch (key) {
      case 'rec_track_regularly': return loc.rec_track_regularly;
      case 'rec_balanced_diet': return loc.rec_balanced_diet;
      case 'rec_schedule_checkup': return loc.rec_schedule_checkup;
      case 'rec_monitor_cycle': return loc.rec_monitor_cycle;
      case 'rec_stress_management': return loc.rec_stress_management;
      case 'rec_consult_gynecologist': return loc.rec_consult_gynecologist;
      case 'rec_request_bloodwork': return loc.rec_request_bloodwork;
      case 'rec_symptom_diary': return loc.rec_symptom_diary;
      default: return key;
    }
  }

  String _getPcosTypeName(AppLocalizations loc, String type) {
    switch (type) {
      case 'Insulin-resistant': return loc.type_insulin_resistant;
      case 'Androgenic': return loc.type_androgenic;
      case 'Adrenal': return loc.type_adrenal;
      default: return type;
    }
  }
}
