import 'package:isar/isar.dart';

import '../../../core/isar/isar_service.dart';
import '../../../core/isar/schemas/insight_cache.dart';

// ──────────────────────────────────────────────────────────────
//  Insight cache service
// ──────────────────────────────────────────────────────────────

/// Caches AI-generated insights locally using Isar so the user
/// always has access to their last insight even when offline.
///
/// Each cached insight records whether it came from the Gemini
/// API ([isFromAi] = true) or from the local detection engine.
class InsightCacheService {
  final IsarService _isarService;

  InsightCacheService({IsarService? isarService})
      : _isarService = isarService ?? IsarService();

  // ── Save ─────────────────────────────────────────────────────

  /// Persists an insight string to the local Isar database.
  ///
  /// [insight]  – the insight text to cache.
  /// [isFromAi] – `true` if this was generated by Gemini,
  ///              `false` if it came from the detection engine.
  Future<int> saveInsight(String insight, {bool isFromAi = true}) async {
    try {
      final isar = await _isarService.db;

      final entry = InsightCache()
        ..insightText = insight
        ..generatedAt = DateTime.now()
        ..expiresAt = DateTime.now().add(const Duration(hours: 24))
        ..isFromAi = isFromAi;

      late int id;
      await isar.writeTxn(() async {
        id = await isar.insightCaches.put(entry);
      });

      return id;
    } catch (e) {
      throw InsightCacheException('Failed to save insight: $e');
    }
  }

  // ── Read ─────────────────────────────────────────────────────

  /// Returns the most recently cached insight, or `null` if the
  /// cache is empty.
  Future<InsightCache?> getLatestInsight() async {
    try {
      final isar = await _isarService.db;

      return await isar.insightCaches
          .where()
          .sortByGeneratedAtDesc()
          .findFirst();
    } catch (e) {
      throw InsightCacheException('Failed to fetch latest insight: $e');
    }
  }

  /// Returns all cached insights, newest first.
  Future<List<InsightCache>> getAllInsights() async {
    try {
      final isar = await _isarService.db;

      return await isar.insightCaches
          .where()
          .sortByGeneratedAtDesc()
          .findAll();
    } catch (e) {
      throw InsightCacheException('Failed to fetch insights: $e');
    }
  }

  // ── Cleanup ──────────────────────────────────────────────────

  /// Removes all insights whose [expiresAt] is in the past.
  Future<void> clearExpired() async {
    try {
      final isar = await _isarService.db;
      final now = DateTime.now();

      await isar.writeTxn(() async {
        final expired = await isar.insightCaches
            .filter()
            .expiresAtIsNotNull()
            .expiresAtLessThan(now)
            .findAll();

        final ids = expired.map((e) => e.id).toList();
        await isar.insightCaches.deleteAll(ids);
      });
    } catch (e) {
      throw InsightCacheException('Failed to clear expired insights: $e');
    }
  }

  /// Clears the entire insight cache.
  Future<void> clearAll() async {
    try {
      final isar = await _isarService.db;
      await isar.writeTxn(() async {
        await isar.insightCaches.clear();
      });
    } catch (e) {
      throw InsightCacheException('Failed to clear insight cache: $e');
    }
  }
}

// ──────────────────────────────────────────────────────────────
//  Custom exception
// ──────────────────────────────────────────────────────────────

/// Thrown when an [InsightCacheService] operation fails.
class InsightCacheException implements Exception {
  final String message;
  const InsightCacheException(this.message);

  @override
  String toString() => 'InsightCacheException: $message';
}
